/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CookieOptIn {
    'config': any;
    'toggleCookeieOptInModal': () => Promise<void>;
  }
}

declare global {


  interface HTMLCookieOptInElement extends Components.CookieOptIn, HTMLStencilElement {}
  var HTMLCookieOptInElement: {
    prototype: HTMLCookieOptInElement;
    new (): HTMLCookieOptInElement;
  };
  interface HTMLElementTagNameMap {
    'cookie-opt-in': HTMLCookieOptInElement;
  }
}

declare namespace LocalJSX {
  interface CookieOptIn {
    'config'?: any;
  }

  interface IntrinsicElements {
    'cookie-opt-in': CookieOptIn;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'cookie-opt-in': LocalJSX.CookieOptIn & JSXBase.HTMLAttributes<HTMLCookieOptInElement>;
    }
  }
}


